import type { ReceiptExtractionResult } from "./types";

/**
 * Mock extraction based on a realistic K-Supermarket receipt.
 * Used when Azure OpenAI credentials are not configured.
 */
export const MOCK_EXTRACTION_RESULT: ReceiptExtractionResult = {
  store: { name: "K-Supermarket Perkkaa", city: "Espoo", country: "Finland" },
  purchase_date: new Date().toISOString().slice(0, 10),
  currency: "EUR",
  items: [
    {
      raw_name_original: "Valio Eila kevytmaitoj 1,75l",
      raw_name_english: "Valio Eila light milk 1.75L",
      canonical_name_en: "Valio Eila Light Milk",
      brand: "Valio",
      category_en: "Dairy",
      quantity: 1,
      size_value: 1.75,
      size_unit: "l",
      weight_value: null,
      weight_unit: null,
      unit_price: 2.88,
      price_per_kg: null,
      price_per_l: null,
      line_total: 2.88,
      is_weighted: false,
      confidence: 0.97,
    },
    {
      raw_name_original: "K-Menu vehnäpaahto 500g",
      raw_name_english: "K-Menu wheat toast 500g",
      canonical_name_en: "K-Menu White Bread",
      brand: "K-Menu",
      category_en: "Bakery",
      quantity: 1,
      size_value: 500,
      size_unit: "g",
      weight_value: null,
      weight_unit: null,
      unit_price: 0.89,
      price_per_kg: null,
      price_per_l: null,
      line_total: 0.89,
      is_weighted: false,
      confidence: 0.94,
    },
    {
      raw_name_original: "Sipuli Suomi",
      raw_name_english: "Onion Finland",
      canonical_name_en: "Onion",
      brand: null,
      category_en: "Produce",
      quantity: 1,
      size_value: null,
      size_unit: null,
      weight_value: 1.011,
      weight_unit: "kg",
      unit_price: null,
      price_per_kg: 0.89,
      price_per_l: null,
      line_total: 0.9,
      is_weighted: true,
      confidence: 0.92,
    },
    {
      raw_name_original: "Kukkakaali",
      raw_name_english: "Cauliflower",
      canonical_name_en: "Cauliflower",
      brand: null,
      category_en: "Produce",
      quantity: 1,
      size_value: null,
      size_unit: null,
      weight_value: 0.652,
      weight_unit: "kg",
      unit_price: null,
      price_per_kg: 3.49,
      price_per_l: null,
      line_total: 2.28,
      is_weighted: true,
      confidence: 0.9,
    },
  ],
};
